import { debateType, opinionType } from './types';

const peppaOpinions: opinionType[] = [
  {
    author: 'GenZKid',
    stance: 'yes',
    amount: 150,
    text: 'Peppa is peak comedy, absolute sigma energy',
    timestamp: '2m ago',
  },
  {
    author: 'BoomerDad',
    stance: 'no',
    amount: 200,
    text: 'This show is annoying and teaches bad behavior',
    timestamp: '4m ago',
  },
  {
    author: 'MemeLord2024',
    stance: 'yes',
    amount: 300,
    text: 'Peppa memes hit different, pure alpha content',
    timestamp: '6m ago',
  },
  {
    author: 'ParentingExpert',
    stance: 'no',
    amount: 120,
    text: 'Kids copying Peppa behavior is a real problem',
    timestamp: '8m ago',
  },
  { author: 'TikTokUser', stance: 'yes', amount: 80, text: '', timestamp: '10m ago' },
  {
    author: 'ChildPsych',
    stance: 'no',
    amount: 250,
    text: 'The bratty behavior is genuinely harmful',
    timestamp: '12m ago',
  },
];

const gazaOpinions: opinionType[] = [
  {
    author: 'PeaceAdvocate',
    stance: 'no',
    amount: 400,
    text: 'Civilian casualties are never justified',
    timestamp: '1m ago',
  },
  {
    author: 'SecurityExpert',
    stance: 'yes',
    amount: 350,
    text: 'Self-defense is a fundamental right',
    timestamp: '3m ago',
  },
  {
    author: 'HumanRights_Observer',
    stance: 'no',
    amount: 500,
    text: 'International law violations are clear',
    timestamp: '5m ago',
  },
  {
    author: 'MiddleEastAnalyst',
    stance: 'yes',
    amount: 280,
    text: 'Complex situation requires decisive action',
    timestamp: '7m ago',
  },
  {
    author: 'DiplomaticSolution',
    stance: 'no',
    amount: 320,
    text: 'Violence only breeds more violence',
    timestamp: '9m ago',
  },
  { author: 'Realist123', stance: 'yes', amount: 150, text: '', timestamp: '11m ago' },
];

const communismOpinions: opinionType[] = [
  {
    author: 'MarxistStudent',
    stance: 'yes',
    amount: 250,
    text: 'Capitalism has failed, time for true equality',
    timestamp: '3m ago',
  },
  {
    author: 'HistoryBuff',
    stance: 'no',
    amount: 400,
    text: 'Every communist state has collapsed or become authoritarian',
    timestamp: '5m ago',
  },
  {
    author: 'WorkerRights',
    stance: 'yes',
    amount: 180,
    text: 'Workers deserve to own the means of production',
    timestamp: '7m ago',
  },
  {
    author: 'EconProfessor',
    stance: 'no',
    amount: 350,
    text: 'Central planning cannot efficiently allocate resources',
    timestamp: '9m ago',
  },
  {
    author: 'YoungIdealist',
    stance: 'yes',
    amount: 120,
    text: 'We need a system that puts people over profit',
    timestamp: '11m ago',
  },
  {
    author: 'BusinessOwner',
    stance: 'no',
    amount: 300,
    text: 'Innovation dies under communist systems',
    timestamp: '13m ago',
  },
];

const magaOpinions: opinionType[] = [
  {
    author: 'PatriotFreedom',
    stance: 'yes',
    amount: 500,
    text: 'America First policies created real prosperity',
    timestamp: '1m ago',
  },
  {
    author: 'DemocracyDefender',
    stance: 'no',
    amount: 450,
    text: 'Dangerous rhetoric that undermines democratic institutions',
    timestamp: '3m ago',
  },
  {
    author: 'WorkingClassJoe',
    stance: 'yes',
    amount: 200,
    text: 'Finally a movement that speaks for forgotten Americans',
    timestamp: '5m ago',
  },
  {
    author: 'ConstitutionalLawyer',
    stance: 'no',
    amount: 380,
    text: 'Constitutional norms matter more than populist appeal',
    timestamp: '7m ago',
  },
  {
    author: 'SmallTownResident',
    stance: 'yes',
    amount: 150,
    text: 'Brought manufacturing jobs back to our community',
    timestamp: '9m ago',
  },
  { author: 'PoliticalScience_Student', stance: 'no', amount: 220, text: '', timestamp: '11m ago' },
];

const billionairesOpinions: opinionType[] = [
  {
    author: 'SocialJustice_Warrior',
    stance: 'no',
    amount: 600,
    text: 'No ethical way to accumulate that much wealth',
    timestamp: '2m ago',
  },
  {
    author: 'EntrepreneurLife',
    stance: 'yes',
    amount: 400,
    text: 'They create jobs and drive innovation forward',
    timestamp: '4m ago',
  },
  {
    author: 'TaxTheRich',
    stance: 'no',
    amount: 350,
    text: 'Extreme wealth inequality destroys democracy',
    timestamp: '6m ago',
  },
  {
    author: 'CapitalistRealist',
    stance: 'yes',
    amount: 300,
    text: 'Free market rewards value creation',
    timestamp: '8m ago',
  },
  {
    author: 'EconomicsPhD',
    stance: 'no',
    amount: 250,
    text: 'Wealth concentration stifles economic mobility',
    timestamp: '10m ago',
  },
  {
    author: 'InvestorMike',
    stance: 'yes',
    amount: 500,
    text: 'Philanthropy does more good than government programs',
    timestamp: '12m ago',
  },
];

const covidVaccineOpinions: opinionType[] = [
  {
    author: 'PublicHealthDoc',
    stance: 'yes',
    amount: 800,
    text: 'Prevented millions of deaths and hospitalizations',
    timestamp: '1m ago',
  },
  {
    author: 'SkepticalParent',
    stance: 'no',
    amount: 300,
    text: 'Too rushed, long-term effects unknown',
    timestamp: '3m ago',
  },
  {
    author: 'ICU_Nurse',
    stance: 'yes',
    amount: 450,
    text: 'Saw firsthand how vaccines saved lives',
    timestamp: '5m ago',
  },
  {
    author: 'NaturalImmunity',
    stance: 'no',
    amount: 200,
    text: 'Natural immunity is superior to artificial',
    timestamp: '7m ago',
  },
  {
    author: 'Epidemiologist',
    stance: 'yes',
    amount: 600,
    text: 'Data clearly shows massive benefit',
    timestamp: '9m ago',
  },
  {
    author: 'FreedomFighter',
    stance: 'no',
    amount: 250,
    text: 'Medical choice should never be mandated',
    timestamp: '11m ago',
  },
];

export const mockDebates: debateType[] = [
  {
    opinionId: 1,
    title: 'Peppa?',
    description: 'Is Peppa Pig genuinely entertaining content or just annoying cringe?',
    image: '/debates/peppa.png',
    trend: [
      42, 38, 45, 41, 47, 52, 49, 54, 58, 53, 56, 61, 58, 62, 59, 55, 52, 48, 51, 47, 44, 49, 53,
      56, 52, 55, 58, 54, 57, 55,
    ],
    yesPercent: 55,
    noPercent: 45,
    yesPrice: 0.55,
    noPrice: 0.45,
    totalLiquidity: 8500,
    participants: 28,
    lastUpdated: '1m ago',
    opinionStream: peppaOpinions,
  },
  {
    opinionId: 2,
    title: 'Israel military operation in gaza?',
    description: 'Is the current military operation in Gaza justified and necessary?',
    image: '/debates/gaza.png',
    trend: [
      58, 55, 52, 48, 45, 49, 52, 48, 44, 41, 38, 42, 45, 48, 44, 47, 51, 54, 50, 47, 44, 48, 51,
      49, 52, 48, 45, 49, 53, 50,
    ],
    yesPercent: 50,
    noPercent: 50,
    yesPrice: 0.5,
    noPrice: 0.5,
    totalLiquidity: 25000,
    participants: 67,
    lastUpdated: '2m ago',
    opinionStream: gazaOpinions,
  },
  {
    opinionId: 3,
    title: 'Communism?',
    description: 'Is communism a viable economic and political system for the modern world?',
    image: '/debates/communism.png',
    trend: [
      48, 45, 42, 39, 35, 32, 28, 31, 35, 38, 34, 30, 27, 31, 34, 37, 33, 30, 34, 37, 40, 36, 33,
      30, 33, 36, 39, 35, 32, 38,
    ],
    yesPercent: 38,
    noPercent: 62,
    yesPrice: 0.38,
    noPrice: 0.62,
    totalLiquidity: 12000,
    participants: 34,
    lastUpdated: '3m ago',
    opinionStream: communismOpinions,
  },
  {
    opinionId: 4,
    title: 'MAGA?',
    description: 'Is the Make America Great Again movement beneficial for the United States?',
    image: '/debates/maga.png',
    trend: [
      50, 55, 59, 67, 55, 69, 75, 64, 73, 79, 87, 79, 72, 81, 74, 66, 61, 55, 40, 52, 52, 55, 49,
      43, 37, 44, 39, 20, 28, 22,
    ],
    yesPercent: 22,
    noPercent: 78,
    yesPrice: 0.5,
    noPrice: 0.5,
    totalLiquidity: 35000,
    participants: 89,
    lastUpdated: '4m ago',
    opinionStream: magaOpinions,
  },
  {
    opinionId: 5,
    title: 'Billionaires?',
    description: 'Should billionaires be allowed to exist in a fair society?',
    image: '/debates/billionaires.png',
    trend: [
      35, 32, 28, 25, 22, 19, 16, 18, 21, 24, 20, 17, 14, 12, 15, 18, 21, 19, 16, 13, 11, 14, 17,
      20, 18, 15, 12, 16, 19, 22,
    ],
    yesPercent: 22,
    noPercent: 78,
    yesPrice: 0.22,
    noPrice: 0.78,
    totalLiquidity: 18000,
    participants: 52,
    lastUpdated: '5m ago',
    opinionStream: billionairesOpinions,
  },
  {
    opinionId: 6,
    title: 'COVID vaccines?',
    description: 'Were COVID-19 vaccines safe and effective public health measures?',
    image: '/debates/vaccines.png',
    trend: [
      78, 75, 79, 82, 80, 77, 74, 71, 68, 72, 75, 78, 81, 79, 76, 73, 77, 80, 83, 81, 78, 75, 79,
      82, 80, 77, 74, 78, 81, 81,
    ],
    yesPercent: 81,
    noPercent: 19,
    yesPrice: 0.81,
    noPrice: 0.19,
    totalLiquidity: 42000,
    participants: 156,
    lastUpdated: '6m ago',
    opinionStream: covidVaccineOpinions,
  },
];
